#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARGSAVehicleApi' {
    Context 'Invoke-RGSAVehicleAvailableAvailableGet' {
        It 'Test Invoke-RGSAVehicleAvailableAvailableGet' {
            #$TestResult = Invoke-RGSAVehicleAvailableAvailableGet -Available "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleCompanyIDCompIdGet' {
        It 'Test Invoke-RGSAVehicleCompanyIDCompIdGet' {
            #$TestResult = Invoke-RGSAVehicleCompanyIDCompIdGet -CompId "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleGet' {
        It 'Test Invoke-RGSAVehicleGet' {
            #$TestResult = Invoke-RGSAVehicleGet -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleIdGet' {
        It 'Test Invoke-RGSAVehicleIdGet' {
            #$TestResult = Invoke-RGSAVehicleIdGet -Id "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleLicenseNumberLicensenoGet' {
        It 'Test Invoke-RGSAVehicleLicenseNumberLicensenoGet' {
            #$TestResult = Invoke-RGSAVehicleLicenseNumberLicensenoGet -Licenseno "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleMakeMakeGet' {
        It 'Test Invoke-RGSAVehicleMakeMakeGet' {
            #$TestResult = Invoke-RGSAVehicleMakeMakeGet -Make "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleVINVinGet' {
        It 'Test Invoke-RGSAVehicleVINVinGet' {
            #$TestResult = Invoke-RGSAVehicleVINVinGet -Vin "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSAVehicleYearModelyearGet' {
        It 'Test Invoke-RGSAVehicleYearModelyearGet' {
            #$TestResult = Invoke-RGSAVehicleYearModelyearGet -Modelyear "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
