#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARGSATerritoryApi' {
    Context 'Invoke-RGSATerritoryAvailableAvailableGet' {
        It 'Test Invoke-RGSATerritoryAvailableAvailableGet' {
            #$TestResult = Invoke-RGSATerritoryAvailableAvailableGet -Available "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSATerritoryCompanyIDCompIdGet' {
        It 'Test Invoke-RGSATerritoryCompanyIDCompIdGet' {
            #$TestResult = Invoke-RGSATerritoryCompanyIDCompIdGet -CompId "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSATerritoryGet' {
        It 'Test Invoke-RGSATerritoryGet' {
            #$TestResult = Invoke-RGSATerritoryGet -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSATerritoryIdGet' {
        It 'Test Invoke-RGSATerritoryIdGet' {
            #$TestResult = Invoke-RGSATerritoryIdGet -Id "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
