#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARGSALeadFormApi' {
    Context 'Invoke-RGSALeadFormSubmitPost' {
        It 'Test Invoke-RGSALeadFormSubmitPost' {
            #$TestResult = Invoke-RGSALeadFormSubmitPost -ApiKey "TEST_VALUE" -LeadForm "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
