#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARGSADiscountCodeApi' {
    Context 'Invoke-RGSADiscountCodeAvailableAvailableGet' {
        It 'Test Invoke-RGSADiscountCodeAvailableAvailableGet' {
            #$TestResult = Invoke-RGSADiscountCodeAvailableAvailableGet -Available "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeAvailableOnHandheldHandheldGet' {
        It 'Test Invoke-RGSADiscountCodeAvailableOnHandheldHandheldGet' {
            #$TestResult = Invoke-RGSADiscountCodeAvailableOnHandheldHandheldGet -Handheld "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeAvailableOnWebWebavailGet' {
        It 'Test Invoke-RGSADiscountCodeAvailableOnWebWebavailGet' {
            #$TestResult = Invoke-RGSADiscountCodeAvailableOnWebWebavailGet -Webavail "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeDollarDiscountDollardiscGet' {
        It 'Test Invoke-RGSADiscountCodeDollarDiscountDollardiscGet' {
            #$TestResult = Invoke-RGSADiscountCodeDollarDiscountDollardiscGet -Dollardisc "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeGet' {
        It 'Test Invoke-RGSADiscountCodeGet' {
            #$TestResult = Invoke-RGSADiscountCodeGet -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeIdGet' {
        It 'Test Invoke-RGSADiscountCodeIdGet' {
            #$TestResult = Invoke-RGSADiscountCodeIdGet -Id "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodeIsSurchargeSurchargeGet' {
        It 'Test Invoke-RGSADiscountCodeIsSurchargeSurchargeGet' {
            #$TestResult = Invoke-RGSADiscountCodeIsSurchargeSurchargeGet -Surcharge "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSADiscountCodePermanentPermanentGet' {
        It 'Test Invoke-RGSADiscountCodePermanentPermanentGet' {
            #$TestResult = Invoke-RGSADiscountCodePermanentPermanentGet -Permanent "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
