#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARGSASubdivisionApi' {
    Context 'Invoke-RGSASubdivisionAvailableAvailableGet' {
        It 'Test Invoke-RGSASubdivisionAvailableAvailableGet' {
            #$TestResult = Invoke-RGSASubdivisionAvailableAvailableGet -Available "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSASubdivisionCompanyIDCompIdGet' {
        It 'Test Invoke-RGSASubdivisionCompanyIDCompIdGet' {
            #$TestResult = Invoke-RGSASubdivisionCompanyIDCompIdGet -CompId "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSASubdivisionGet' {
        It 'Test Invoke-RGSASubdivisionGet' {
            #$TestResult = Invoke-RGSASubdivisionGet -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSASubdivisionIdGet' {
        It 'Test Invoke-RGSASubdivisionIdGet' {
            #$TestResult = Invoke-RGSASubdivisionIdGet -Id "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-RGSASubdivisionNameSubnameGet' {
        It 'Test Invoke-RGSASubdivisionNameSubnameGet' {
            #$TestResult = Invoke-RGSASubdivisionNameSubnameGet -Subname "TEST_VALUE" -ApiKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
