#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Due030
No description available.
.PARAMETER Due3145
No description available.
.PARAMETER Due4660
No description available.
.PARAMETER Due6190
No description available.
.PARAMETER DueOver90
No description available.
.PARAMETER Num030
No description available.
.PARAMETER Num3145
No description available.
.PARAMETER Num4660
No description available.
.PARAMETER Num6190
No description available.
.PARAMETER NumOver90
No description available.
.PARAMETER TotalPrepayRemaining
No description available.
.PARAMETER CreditsPrepayCustomers
No description available.
.PARAMETER CreditsNonPrepay
No description available.
.PARAMETER RemitDuePrepayCustomers
No description available.
.PARAMETER RemitDueNonPrepayCustomers
No description available.
.OUTPUTS

BalanceAnalysisExtendedSummary<PSCustomObject>
#>

function Initialize-RgSaBalanceAnalysisExtendedSummary {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Due030},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Due3145},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Due4660},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${Due6190},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${DueOver90},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Num030},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Num3145},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Num4660},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Num6190},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${NumOver90},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${TotalPrepayRemaining},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${CreditsPrepayCustomers},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${CreditsNonPrepay},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${RemitDuePrepayCustomers},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${RemitDueNonPrepayCustomers}
    )

    Process {
        'Creating PSCustomObject: RealGreenSAPS => RgSaBalanceAnalysisExtendedSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "due0_30" = ${Due030}
            "due31_45" = ${Due3145}
            "due46_60" = ${Due4660}
            "due61_90" = ${Due6190}
            "dueOver90" = ${DueOver90}
            "num0_30" = ${Num030}
            "num31_45" = ${Num3145}
            "num46_60" = ${Num4660}
            "num61_90" = ${Num6190}
            "numOver90" = ${NumOver90}
            "totalPrepayRemaining" = ${TotalPrepayRemaining}
            "creditsPrepayCustomers" = ${CreditsPrepayCustomers}
            "creditsNonPrepay" = ${CreditsNonPrepay}
            "remitDuePrepayCustomers" = ${RemitDuePrepayCustomers}
            "remitDueNonPrepayCustomers" = ${RemitDueNonPrepayCustomers}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BalanceAnalysisExtendedSummary<PSCustomObject>

.DESCRIPTION

Convert from JSON to BalanceAnalysisExtendedSummary<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BalanceAnalysisExtendedSummary<PSCustomObject>
#>
function ConvertFrom-RgSaJsonToBalanceAnalysisExtendedSummary {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: RealGreenSAPS => RgSaBalanceAnalysisExtendedSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RgSaBalanceAnalysisExtendedSummary
        $AllProperties = ("due0_30", "due31_45", "due46_60", "due61_90", "dueOver90", "num0_30", "num31_45", "num46_60", "num61_90", "numOver90", "totalPrepayRemaining", "creditsPrepayCustomers", "creditsNonPrepay", "remitDuePrepayCustomers", "remitDueNonPrepayCustomers")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "due0_30"))) { #optional property not found
            $Due030 = $null
        } else {
            $Due030 = $JsonParameters.PSobject.Properties["due0_30"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "due31_45"))) { #optional property not found
            $Due3145 = $null
        } else {
            $Due3145 = $JsonParameters.PSobject.Properties["due31_45"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "due46_60"))) { #optional property not found
            $Due4660 = $null
        } else {
            $Due4660 = $JsonParameters.PSobject.Properties["due46_60"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "due61_90"))) { #optional property not found
            $Due6190 = $null
        } else {
            $Due6190 = $JsonParameters.PSobject.Properties["due61_90"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dueOver90"))) { #optional property not found
            $DueOver90 = $null
        } else {
            $DueOver90 = $JsonParameters.PSobject.Properties["dueOver90"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "num0_30"))) { #optional property not found
            $Num030 = $null
        } else {
            $Num030 = $JsonParameters.PSobject.Properties["num0_30"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "num31_45"))) { #optional property not found
            $Num3145 = $null
        } else {
            $Num3145 = $JsonParameters.PSobject.Properties["num31_45"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "num46_60"))) { #optional property not found
            $Num4660 = $null
        } else {
            $Num4660 = $JsonParameters.PSobject.Properties["num46_60"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "num61_90"))) { #optional property not found
            $Num6190 = $null
        } else {
            $Num6190 = $JsonParameters.PSobject.Properties["num61_90"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numOver90"))) { #optional property not found
            $NumOver90 = $null
        } else {
            $NumOver90 = $JsonParameters.PSobject.Properties["numOver90"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalPrepayRemaining"))) { #optional property not found
            $TotalPrepayRemaining = $null
        } else {
            $TotalPrepayRemaining = $JsonParameters.PSobject.Properties["totalPrepayRemaining"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "creditsPrepayCustomers"))) { #optional property not found
            $CreditsPrepayCustomers = $null
        } else {
            $CreditsPrepayCustomers = $JsonParameters.PSobject.Properties["creditsPrepayCustomers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "creditsNonPrepay"))) { #optional property not found
            $CreditsNonPrepay = $null
        } else {
            $CreditsNonPrepay = $JsonParameters.PSobject.Properties["creditsNonPrepay"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "remitDuePrepayCustomers"))) { #optional property not found
            $RemitDuePrepayCustomers = $null
        } else {
            $RemitDuePrepayCustomers = $JsonParameters.PSobject.Properties["remitDuePrepayCustomers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "remitDueNonPrepayCustomers"))) { #optional property not found
            $RemitDueNonPrepayCustomers = $null
        } else {
            $RemitDueNonPrepayCustomers = $JsonParameters.PSobject.Properties["remitDueNonPrepayCustomers"].value
        }

        $PSO = [PSCustomObject]@{
            "due0_30" = ${Due030}
            "due31_45" = ${Due3145}
            "due46_60" = ${Due4660}
            "due61_90" = ${Due6190}
            "dueOver90" = ${DueOver90}
            "num0_30" = ${Num030}
            "num31_45" = ${Num3145}
            "num46_60" = ${Num4660}
            "num61_90" = ${Num6190}
            "numOver90" = ${NumOver90}
            "totalPrepayRemaining" = ${TotalPrepayRemaining}
            "creditsPrepayCustomers" = ${CreditsPrepayCustomers}
            "creditsNonPrepay" = ${CreditsNonPrepay}
            "remitDuePrepayCustomers" = ${RemitDuePrepayCustomers}
            "remitDueNonPrepayCustomers" = ${RemitDueNonPrepayCustomers}
        }

        return $PSO
    }

}

