#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CompanyIDs
No description available.
.PARAMETER CustomerType
No description available.
.PARAMETER Statuses
No description available.
.OUTPUTS

CreditHoldSummaryCriteria<PSCustomObject>
#>

function Initialize-RGSACreditHoldSummaryCriteria {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${CompanyIDs},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CustomerType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Statuses}
    )

    Process {
        'Creating PSCustomObject: RealGreenSaPS => RGSACreditHoldSummaryCriteria' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$CustomerType -and $CustomerType.length -gt 1) {
            throw "invalid value for 'CustomerType', the character length must be smaller than or equal to 1."
        }

        if (!$CustomerType -and $CustomerType.length -lt 1) {
            throw "invalid value for 'CustomerType', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "companyIDs" = ${CompanyIDs}
            "customerType" = ${CustomerType}
            "statuses" = ${Statuses}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreditHoldSummaryCriteria<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreditHoldSummaryCriteria<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreditHoldSummaryCriteria<PSCustomObject>
#>
function ConvertFrom-RGSAJsonToCreditHoldSummaryCriteria {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: RealGreenSaPS => RGSACreditHoldSummaryCriteria' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RGSACreditHoldSummaryCriteria
        $AllProperties = ("companyIDs", "customerType", "statuses")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyIDs"))) { #optional property not found
            $CompanyIDs = $null
        } else {
            $CompanyIDs = $JsonParameters.PSobject.Properties["companyIDs"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customerType"))) { #optional property not found
            $CustomerType = $null
        } else {
            $CustomerType = $JsonParameters.PSobject.Properties["customerType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "statuses"))) { #optional property not found
            $Statuses = $null
        } else {
            $Statuses = $JsonParameters.PSobject.Properties["statuses"].value
        }

        $PSO = [PSCustomObject]@{
            "companyIDs" = ${CompanyIDs}
            "customerType" = ${CustomerType}
            "statuses" = ${Statuses}
        }

        return $PSO
    }

}

