#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum DateBasedOn.

.DESCRIPTION

No description available.
#>

enum DateBasedOn {
    # enum value: "SoldDate"
    SoldDate
    # enum value: "ConfirmDate"
    ConfirmDate
    # enum value: "EstimateRequestedDate"
    EstimateRequestedDate
    # enum value: "ScheduleDate"
    ScheduleDate
    # enum value: "EstimateGivenDate"
    EstimateGivenDate
    # enum value: "PrintedDate"
    PrintedDate
}

