#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PhoneTypes.

.DESCRIPTION

No description available.
#>

enum PhoneTypes {
    # enum value: "None"
    None
    # enum value: "Cell"
    Cell
    # enum value: "Fax"
    Fax
    # enum value: "Home"
    Home
    # enum value: "Other"
    Other
    # enum value: "Text"
    Text
    # enum value: "Work"
    Work
}

