#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Description
No description available.
.PARAMETER Available
No description available.
.PARAMETER MaxSize
No description available.
.PARAMETER MaxRate
No description available.
.PARAMETER MaxManHour
No description available.
.PARAMETER DescriptionFrench
No description available.
.PARAMETER DescriptionSpanish
No description available.
.OUTPUTS

PriceTable<PSCustomObject>
#>

function Initialize-RgSaPriceTable {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Available},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${MaxSize},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${MaxRate},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${MaxManHour},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DescriptionFrench},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DescriptionSpanish}
    )

    Process {
        'Creating PSCustomObject: RealGreenSAPS => RgSaPriceTable' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "description" = ${Description}
            "available" = ${Available}
            "maxSize" = ${MaxSize}
            "maxRate" = ${MaxRate}
            "maxManHour" = ${MaxManHour}
            "descriptionFrench" = ${DescriptionFrench}
            "descriptionSpanish" = ${DescriptionSpanish}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PriceTable<PSCustomObject>

.DESCRIPTION

Convert from JSON to PriceTable<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PriceTable<PSCustomObject>
#>
function ConvertFrom-RgSaJsonToPriceTable {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: RealGreenSAPS => RgSaPriceTable' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RgSaPriceTable
        $AllProperties = ("id", "description", "available", "maxSize", "maxRate", "maxManHour", "descriptionFrench", "descriptionSpanish")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "available"))) { #optional property not found
            $Available = $null
        } else {
            $Available = $JsonParameters.PSobject.Properties["available"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxSize"))) { #optional property not found
            $MaxSize = $null
        } else {
            $MaxSize = $JsonParameters.PSobject.Properties["maxSize"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxRate"))) { #optional property not found
            $MaxRate = $null
        } else {
            $MaxRate = $JsonParameters.PSobject.Properties["maxRate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxManHour"))) { #optional property not found
            $MaxManHour = $null
        } else {
            $MaxManHour = $JsonParameters.PSobject.Properties["maxManHour"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "descriptionFrench"))) { #optional property not found
            $DescriptionFrench = $null
        } else {
            $DescriptionFrench = $JsonParameters.PSobject.Properties["descriptionFrench"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "descriptionSpanish"))) { #optional property not found
            $DescriptionSpanish = $null
        } else {
            $DescriptionSpanish = $JsonParameters.PSobject.Properties["descriptionSpanish"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "description" = ${Description}
            "available" = ${Available}
            "maxSize" = ${MaxSize}
            "maxRate" = ${MaxRate}
            "maxManHour" = ${MaxManHour}
            "descriptionFrench" = ${DescriptionFrench}
            "descriptionSpanish" = ${DescriptionSpanish}
        }

        return $PSO
    }

}

