#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum ProgramJobLength.

.DESCRIPTION

No description available.
#>

enum ProgramJobLength {
    # enum value: "BothFullAndPartial"
    BothFullAndPartial
    # enum value: "PartialProgramJobsOnly"
    PartialProgramJobsOnly
    # enum value: "FullProgramJobsOnly"
    FullProgramJobsOnly
}

