#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum StatementFrequency.

.DESCRIPTION

No description available.
#>

enum StatementFrequency {
    # enum value: "ForRemitBalance"
    ForRemitBalance
    # enum value: "Never"
    Never
    # enum value: "Always"
    Always
    # enum value: "IncludeInNextBatch"
    IncludeInNextBatch
}

