#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaAddInstallmentResult' {
    Context 'RgSaAddInstallmentResult' {
        It 'Initialize-RgSaAddInstallmentResult' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaAddInstallmentResult -ContractID "TEST_VALUE" -Payments "TEST_VALUE"
            #$NewObject | Should -BeOfType AddInstallmentResult
            #$NewObject.property | Should -Be 0
        }
    }
}
