#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAAddInstallmentResult' {
    Context 'RGSAAddInstallmentResult' {
        It 'Initialize-RGSAAddInstallmentResult' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAAddInstallmentResult -ContractID "TEST_VALUE" -Payments "TEST_VALUE"
            #$NewObject | Should -BeOfType AddInstallmentResult
            #$NewObject.property | Should -Be 0
        }
    }
}
