#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAAPIErrorCodes' {
    Context 'RGSAAPIErrorCodes' {
        It 'Initialize-RGSAAPIErrorCodes' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAAPIErrorCodes
            #$NewObject | Should -BeOfType APIErrorCodes
            #$NewObject.property | Should -Be 0
        }
    }
}
