#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAAPIEmployeeInsert' {
    Context 'RGSAAPIEmployeeInsert' {
        It 'Initialize-RGSAAPIEmployeeInsert' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAAPIEmployeeInsert -EmployeeID "TEST_VALUE" -Name "TEST_VALUE" -CompanyID "TEST_VALUE"
            #$NewObject | Should -BeOfType APIEmployeeInsert
            #$NewObject.property | Should -Be 0
        }
    }
}
