#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaAPIErrorCodes' {
    Context 'RgSaAPIErrorCodes' {
        It 'Initialize-RgSaAPIErrorCodes' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaAPIErrorCodes
            #$NewObject | Should -BeOfType APIErrorCodes
            #$NewObject.property | Should -Be 0
        }
    }
}
