#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaAPIFlagInsert' {
    Context 'RgSaAPIFlagInsert' {
        It 'Initialize-RgSaAPIFlagInsert' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaAPIFlagInsert -Description "TEST_VALUE" -Sort "TEST_VALUE" -Internet "TEST_VALUE" -PrintOnInvoice "TEST_VALUE" -PrintOnEstimate "TEST_VALUE"
            #$NewObject | Should -BeOfType APIFlagInsert
            #$NewObject.property | Should -Be 0
        }
    }
}
