#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaAPIProductInsert' {
    Context 'RgSaAPIProductInsert' {
        It 'Initialize-RgSaAPIProductInsert' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaAPIProductInsert -ProductCode "TEST_VALUE" -Description "TEST_VALUE" -EpaNumber "TEST_VALUE" -OnHand "TEST_VALUE" -UnitCost "TEST_VALUE" -UnitPrice "TEST_VALUE" -ProductCategoryId "TEST_VALUE" -UnitofMeasure "TEST_VALUE" -ProposalNotes "TEST_VALUE" -CrewNotes "TEST_VALUE"
            #$NewObject | Should -BeOfType APIProductInsert
            #$NewObject.property | Should -Be 0
        }
    }
}
