#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaAuditLogSearchCommon' {
    Context 'RgSaAuditLogSearchCommon' {
        It 'Initialize-RgSaAuditLogSearchCommon' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaAuditLogSearchCommon -CompanyIDs "TEST_VALUE" -DateTimeRange "TEST_VALUE"
            #$NewObject | Should -BeOfType AuditLogSearchCommon
            #$NewObject.property | Should -Be 0
        }
    }
}
