#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaBalanceAnalysis' {
    Context 'RgSaBalanceAnalysis' {
        It 'Initialize-RgSaBalanceAnalysis' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaBalanceAnalysis -CompanyID "TEST_VALUE" -Due030 "TEST_VALUE" -Due3145 "TEST_VALUE" -Due4660 "TEST_VALUE" -Due6190 "TEST_VALUE" -DueOver90 "TEST_VALUE" -Num030 "TEST_VALUE" -Num3145 "TEST_VALUE" -Num4660 "TEST_VALUE" -Num6190 "TEST_VALUE" -NumOver90 "TEST_VALUE"
            #$NewObject | Should -BeOfType BalanceAnalysis
            #$NewObject.property | Should -Be 0
        }
    }
}
