#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSABatch' {
    Context 'RGSABatch' {
        It 'Initialize-RGSABatch' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSABatch -Id "TEST_VALUE" -PrintDate "TEST_VALUE" -EmployeeId "TEST_VALUE" -Type "TEST_VALUE" -TypeDescription "TEST_VALUE" -UndoDate "TEST_VALUE" -UndoEmployeeId "TEST_VALUE" -ScheduleDate "TEST_VALUE" -DriveDist "TEST_VALUE" -LunchTime "TEST_VALUE" -LunchLength "TEST_VALUE" -BatchCount "TEST_VALUE"
            #$NewObject | Should -BeOfType Batch
            #$NewObject.property | Should -Be 0
        }
    }
}
