#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaBillType' {
    Context 'RgSaBillType' {
        It 'Initialize-RgSaBillType' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaBillType
            #$NewObject | Should -BeOfType BillType
            #$NewObject.property | Should -Be 0
        }
    }
}
