#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACallAhead' {
    Context 'RGSACallAhead' {
        It 'Initialize-RGSACallAhead' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACallAhead -Id "TEST_VALUE" -CallAheadDescription "TEST_VALUE" -Renewable "TEST_VALUE" -Available "TEST_VALUE" -Highlight "TEST_VALUE" -CallDescFrench "TEST_VALUE" -CallDescSpanish "TEST_VALUE" -NotificationType "TEST_VALUE"
            #$NewObject | Should -BeOfType CallAhead
            #$NewObject.property | Should -Be 0
        }
    }
}
