#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCallLogSimple' {
    Context 'RgSaCallLogSimple' {
        It 'Initialize-RgSaCallLogSimple' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCallLogSimple -CustNo "TEST_VALUE" -EmpId "TEST_VALUE" -ActionReasonID "TEST_VALUE" -Status "TEST_VALUE" -Note "TEST_VALUE" -AuditEmployeeID "TEST_VALUE" -Name "TEST_VALUE" -PhoneNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType CallLogSimple
            #$NewObject.property | Should -Be 0
        }
    }
}
