#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACashInRequest' {
    Context 'RGSACashInRequest' {
        It 'Initialize-RGSACashInRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACashInRequest -DateRange "TEST_VALUE" -CustomDateRange "TEST_VALUE" -DateType "TEST_VALUE" -PostedBy "TEST_VALUE" -PayType "TEST_VALUE" -CustomerStatus "TEST_VALUE" -IsPrepayment "TEST_VALUE" -CustomerType "TEST_VALUE" -Route "TEST_VALUE" -CompanyIDs "TEST_VALUE"
            #$NewObject | Should -BeOfType CashInRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
