#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACAWRegistrationSummary' {
    Context 'RGSACAWRegistrationSummary' {
        It 'Initialize-RGSACAWRegistrationSummary' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACAWRegistrationSummary -ActiveCount "TEST_VALUE" -RegisteredPercent "TEST_VALUE" -AutoPayPercent "TEST_VALUE"
            #$NewObject | Should -BeOfType CAWRegistrationSummary
            #$NewObject.property | Should -Be 0
        }
    }
}
