#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCompany' {
    Context 'RgSaCompany' {
        It 'Initialize-RgSaCompany' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCompany -Id "TEST_VALUE" -CompanyName "TEST_VALUE" -BranchNumber "TEST_VALUE" -AddressLine1 "TEST_VALUE" -AddressLine2 "TEST_VALUE" -AddressLine3 "TEST_VALUE" -State "TEST_VALUE" -AreaCode "TEST_VALUE" -IsDefaultCompany "TEST_VALUE" -Phone1 "TEST_VALUE" -Phone2 "TEST_VALUE" -Fax "TEST_VALUE" -ManagerID "TEST_VALUE" -UnitCodeID "TEST_VALUE" -TaxID1 "TEST_VALUE" -TaxID2 "TEST_VALUE" -TaxID3 "TEST_VALUE" -BusinessStartTime "TEST_VALUE" -BusinessEndTime "TEST_VALUE" -MarketId "TEST_VALUE" -PaymentGateway "TEST_VALUE" -TerminalId "TEST_VALUE" -MerchantId "TEST_VALUE" -CreditCardUsername "TEST_VALUE" -CreditCardPassword "TEST_VALUE" -ReplyEmail "TEST_VALUE" -Url "TEST_VALUE" -DefaultSalesMessageId "TEST_VALUE" -Latitude "TEST_VALUE" -Longitude "TEST_VALUE" -LunchTimeWindowBegin "TEST_VALUE" -LunchTimeWindowEnd "TEST_VALUE" -LunchLength "TEST_VALUE" -LicenseNumber "TEST_VALUE" -BranchNumberAndCompanyName "TEST_VALUE" -SwsBranchCode "TEST_VALUE" -CompanyToken "TEST_VALUE" -SmsNumber "TEST_VALUE" -TcnUser "TEST_VALUE" -TcnPassword "TEST_VALUE" -TcnOptions "TEST_VALUE" -AprUsername "TEST_VALUE" -AprPassword "TEST_VALUE" -AprOptions "TEST_VALUE" -RealgreenCustomerNumber "TEST_VALUE" -CaptivatedAPIKey "TEST_VALUE" -CaptivatedSMSNumber "TEST_VALUE" -TenDlcStatus "TEST_VALUE" -TaxIdNumber "TEST_VALUE" -CnaSmsNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType Company
            #$NewObject.property | Should -Be 0
        }
    }
}
