#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACompanyIDsAndDateRange' {
    Context 'RGSACompanyIDsAndDateRange' {
        It 'Initialize-RGSACompanyIDsAndDateRange' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACompanyIDsAndDateRange -DateRange "TEST_VALUE" -CustomDateRange "TEST_VALUE" -CompanyIDs "TEST_VALUE"
            #$NewObject | Should -BeOfType CompanyIDsAndDateRange
            #$NewObject.property | Should -Be 0
        }
    }
}
