#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAContractPlanStatus' {
    Context 'RGSAContractPlanStatus' {
        It 'Initialize-RGSAContractPlanStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAContractPlanStatus
            #$NewObject | Should -BeOfType ContractPlanStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
