#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCreditHoldSummaryCriteria' {
    Context 'RgSaCreditHoldSummaryCriteria' {
        It 'Initialize-RgSaCreditHoldSummaryCriteria' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCreditHoldSummaryCriteria -CompanyIDs "TEST_VALUE" -CustomerType "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType CreditHoldSummaryCriteria
            #$NewObject.property | Should -Be 0
        }
    }
}
