#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACustomerProperty' {
    Context 'RGSACustomerProperty' {
        It 'Initialize-RGSACustomerProperty' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACustomerProperty -Id "TEST_VALUE" -InventoryTypeID "TEST_VALUE" -CustomerID "TEST_VALUE" -Quantity "TEST_VALUE" -LocationID "TEST_VALUE" -Note "TEST_VALUE" -UnitOfMeasureID "TEST_VALUE" -LocationType "TEST_VALUE" -PropertyItemType "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerProperty
            #$NewObject.property | Should -Be 0
        }
    }
}
