#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCustomerFlagAPIRequest' {
    Context 'RgSaCustomerFlagAPIRequest' {
        It 'Initialize-RgSaCustomerFlagAPIRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCustomerFlagAPIRequest -FlagID "TEST_VALUE" -CompanyIDs "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerFlagAPIRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
