#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCustomerValueRequest' {
    Context 'RgSaCustomerValueRequest' {
        It 'Initialize-RgSaCustomerValueRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCustomerValueRequest -CompanyIDs "TEST_VALUE" -SourceCodes "TEST_VALUE" -ResidentialCommercial "TEST_VALUE" -Seasons "TEST_VALUE" -PostalCodes "TEST_VALUE" -Routes "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerValueRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
