#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSACustomerFlagAPIRequest' {
    Context 'RGSACustomerFlagAPIRequest' {
        It 'Initialize-RGSACustomerFlagAPIRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSACustomerFlagAPIRequest -FlagID "TEST_VALUE" -CompanyIDs "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerFlagAPIRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
