#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCustomerFlagModifierBulk' {
    Context 'RgSaCustomerFlagModifierBulk' {
        It 'Initialize-RgSaCustomerFlagModifierBulk' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCustomerFlagModifierBulk -CustomerNumbers "TEST_VALUE" -Flag "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerFlagModifierBulk
            #$NewObject.property | Should -Be 0
        }
    }
}
