#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaCustomerFlag' {
    Context 'RgSaCustomerFlag' {
        It 'Initialize-RgSaCustomerFlag' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaCustomerFlag -Id "TEST_VALUE" -Flag "TEST_VALUE" -CustomerNumber "TEST_VALUE" -Descriptions "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerFlag
            #$NewObject.property | Should -Be 0
        }
    }
}
