#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaDateRanges' {
    Context 'RgSaDateRanges' {
        It 'Initialize-RgSaDateRanges' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaDateRanges
            #$NewObject | Should -BeOfType DateRanges
            #$NewObject.property | Should -Be 0
        }
    }
}
