#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSADoneByEmployee' {
    Context 'RGSADoneByEmployee' {
        It 'Initialize-RGSADoneByEmployee' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSADoneByEmployee -Id "TEST_VALUE" -ServiceID "TEST_VALUE" -EmployeeID "TEST_VALUE" -EmployeeName "TEST_VALUE" -Percent "TEST_VALUE" -DoneDate "TEST_VALUE" -StarTime "TEST_VALUE" -EndTime "TEST_VALUE" -Created "TEST_VALUE" -Updated "TEST_VALUE"
            #$NewObject | Should -BeOfType DoneByEmployee
            #$NewObject.property | Should -Be 0
        }
    }
}
