#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAEmailPenetration' {
    Context 'RGSAEmailPenetration' {
        It 'Initialize-RGSAEmailPenetration' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAEmailPenetration -WithEmails "TEST_VALUE" -WithoutEmails "TEST_VALUE" -DontEmailMarket "TEST_VALUE" -DontEmailFollowUp "TEST_VALUE"
            #$NewObject | Should -BeOfType EmailPenetration
            #$NewObject.property | Should -Be 0
        }
    }
}
