#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaEmailPenetrationCriteria' {
    Context 'RgSaEmailPenetrationCriteria' {
        It 'Initialize-RgSaEmailPenetrationCriteria' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaEmailPenetrationCriteria -CompanyIDs "TEST_VALUE" -Statuses "TEST_VALUE"
            #$NewObject | Should -BeOfType EmailPenetrationCriteria
            #$NewObject.property | Should -Be 0
        }
    }
}
