#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAIndividualInstallment' {
    Context 'RGSAIndividualInstallment' {
        It 'Initialize-RGSAIndividualInstallment' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAIndividualInstallment -ContractPaymentId "TEST_VALUE" -DueDate "TEST_VALUE" -Amount "TEST_VALUE" -Tax1 "TEST_VALUE" -Tax2 "TEST_VALUE" -Tax3 "TEST_VALUE" -Total "TEST_VALUE" -Billed "TEST_VALUE" -InvoiceNumber "TEST_VALUE" -PrePayId "TEST_VALUE" -PrePayment "TEST_VALUE"
            #$NewObject | Should -BeOfType IndividualInstallment
            #$NewObject.property | Should -Be 0
        }
    }
}
