#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaLeadSourceSummaryRequest' {
    Context 'RgSaLeadSourceSummaryRequest' {
        It 'Initialize-RgSaLeadSourceSummaryRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaLeadSourceSummaryRequest -CompanyIDs "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE" -SourceCodes "TEST_VALUE" -EstimateRequestedDateRange "TEST_VALUE" -CustomDateRange "TEST_VALUE" -EstimateGivenBy "TEST_VALUE" -SoldBy1 "TEST_VALUE" -SoldBy2 "TEST_VALUE"
            #$NewObject | Should -BeOfType LeadSourceSummaryRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
