#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSALocationType' {
    Context 'RGSALocationType' {
        It 'Initialize-RGSALocationType' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSALocationType -Id "TEST_VALUE" -Description "TEST_VALUE" -TranslatedDescription "TEST_VALUE" -SortOrder "TEST_VALUE"
            #$NewObject | Should -BeOfType LocationType
            #$NewObject.property | Should -Be 0
        }
    }
}
