#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaNewSaleCancels' {
    Context 'RgSaNewSaleCancels' {
        It 'Initialize-RgSaNewSaleCancels' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaNewSaleCancels -CancelCount "TEST_VALUE" -CancelDollar "TEST_VALUE" -SalesCount "TEST_VALUE" -SalesDollar "TEST_VALUE"
            #$NewObject | Should -BeOfType NewSaleCancels
            #$NewObject.property | Should -Be 0
        }
    }
}
