#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPackage' {
    Context 'RgSaPackage' {
        It 'Initialize-RgSaPackage' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPackage -Id "TEST_VALUE" -Description "TEST_VALUE" -DesecriptionFrench "TEST_VALUE" -DesecriptionSpanish "TEST_VALUE" -Available "TEST_VALUE" -AnyBranch "TEST_VALUE"
            #$NewObject | Should -BeOfType Package
            #$NewObject.property | Should -Be 0
        }
    }
}
