#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAPackageProgram' {
    Context 'RGSAPackageProgram' {
        It 'Initialize-RGSAPackageProgram' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAPackageProgram -Id "TEST_VALUE" -Code "TEST_VALUE" -Description "TEST_VALUE" -PackageID "TEST_VALUE" -ProgramDefinitionID "TEST_VALUE" -DiscountCode "TEST_VALUE" -ApplyDiscount "TEST_VALUE"
            #$NewObject | Should -BeOfType PackageProgram
            #$NewObject.property | Should -Be 0
        }
    }
}
