#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPhoneSearch' {
    Context 'RgSaPhoneSearch' {
        It 'Initialize-RgSaPhoneSearch' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPhoneSearch -PhoneNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType PhoneSearch
            #$NewObject.property | Should -Be 0
        }
    }
}
