#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPhone' {
    Context 'RgSaPhone' {
        It 'Initialize-RgSaPhone' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPhone -Number "TEST_VALUE" -Type "TEST_VALUE" -PhoneType "TEST_VALUE" -TypeDescription "TEST_VALUE" -IsPreferred "TEST_VALUE"
            #$NewObject | Should -BeOfType Phone
            #$NewObject.property | Should -Be 0
        }
    }
}
