#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAPhone' {
    Context 'RGSAPhone' {
        It 'Initialize-RGSAPhone' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAPhone -Number "TEST_VALUE" -Type "TEST_VALUE" -PhoneType "TEST_VALUE" -TypeDescription "TEST_VALUE" -IsPreferred "TEST_VALUE"
            #$NewObject | Should -BeOfType Phone
            #$NewObject.property | Should -Be 0
        }
    }
}
