#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPrepayCodeLookup' {
    Context 'RgSaPrepayCodeLookup' {
        It 'Initialize-RgSaPrepayCodeLookup' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPrepayCodeLookup -CompanyID "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE"
            #$NewObject | Should -BeOfType PrepayCodeLookup
            #$NewObject.property | Should -Be 0
        }
    }
}
