#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPriceIncreaseCriteria' {
    Context 'RgSaPriceIncreaseCriteria' {
        It 'Initialize-RgSaPriceIncreaseCriteria' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPriceIncreaseCriteria -ProgramIDs "TEST_VALUE" -IncreaseAmount "TEST_VALUE" -IsPercentIncrease "TEST_VALUE" -OnlyIncreaseRenewalPrice "TEST_VALUE"
            #$NewObject | Should -BeOfType PriceIncreaseCriteria
            #$NewObject.property | Should -Be 0
        }
    }
}
