#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPriceRange' {
    Context 'RgSaPriceRange' {
        It 'Initialize-RgSaPriceRange' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPriceRange -Id "TEST_VALUE" -Size "TEST_VALUE" -Rate "TEST_VALUE" -PriceTableID "TEST_VALUE" -EstimatedManHours "TEST_VALUE"
            #$NewObject | Should -BeOfType PriceRange
            #$NewObject.property | Should -Be 0
        }
    }
}
