#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAPriceTable' {
    Context 'RGSAPriceTable' {
        It 'Initialize-RGSAPriceTable' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAPriceTable -Id "TEST_VALUE" -Description "TEST_VALUE" -Available "TEST_VALUE" -MaxSize "TEST_VALUE" -MaxRate "TEST_VALUE" -MaxManHour "TEST_VALUE" -DescriptionFrench "TEST_VALUE" -DescriptionSpanish "TEST_VALUE"
            #$NewObject | Should -BeOfType PriceTable
            #$NewObject.property | Should -Be 0
        }
    }
}
