#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaPriceByTypes' {
    Context 'RgSaPriceByTypes' {
        It 'Initialize-RgSaPriceByTypes' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaPriceByTypes
            #$NewObject | Should -BeOfType PriceByTypes
            #$NewObject.property | Should -Be 0
        }
    }
}
