#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaProductionResult' {
    Context 'RgSaProductionResult' {
        It 'Initialize-RgSaProductionResult' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaProductionResult -TotalServiceCount "TEST_VALUE" -TotalServiceSize "TEST_VALUE" -GrossAmount "TEST_VALUE" -NetAmount "TEST_VALUE" -DiscountAmount "TEST_VALUE" -PrepayDiscountAmount "TEST_VALUE" -TotalHours "TEST_VALUE" -ProductionValue "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductionResult
            #$NewObject.property | Should -Be 0
        }
    }
}
