#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaProductionParams' {
    Context 'RgSaProductionParams' {
        It 'Initialize-RgSaProductionParams' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaProductionParams -CanUseProducts "TEST_VALUE" -CanEnterStartTime "TEST_VALUE" -CanEnterEndTime "TEST_VALUE" -CanEnterCrew "TEST_VALUE" -CanEnterWind "TEST_VALUE" -CanEnterTemperature "TEST_VALUE" -CanEnterPH "TEST_VALUE" -CanSaveAssociatedConditionCodes "TEST_VALUE" -CanEnterConditionCodes "TEST_VALUE" -CanEnterRating "TEST_VALUE" -CanChangeProductionSize "TEST_VALUE" -CanChangeProductionPrice "TEST_VALUE" -PreNotify "TEST_VALUE" -NoScheduleDate "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductionParams
            #$NewObject.property | Should -Be 0
        }
    }
}
