#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAProgramCodes' {
    Context 'RGSAProgramCodes' {
        It 'Initialize-RGSAProgramCodes' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAProgramCodes -ProgramDefinitionID "TEST_VALUE" -ProgramCode "TEST_VALUE" -Description "TEST_VALUE" -Available "TEST_VALUE" -ProgramSpecial "TEST_VALUE" -ProgramType "TEST_VALUE" -UnitCode "TEST_VALUE" -AutoRenew "TEST_VALUE" -Max "TEST_VALUE" -PriceID "TEST_VALUE" -IsNonServiceYear "TEST_VALUE" -IncludeConfirmationLetter "TEST_VALUE" -AnyBranch "TEST_VALUE" -Repeat "TEST_VALUE" -RepeatEvery "TEST_VALUE" -RepeatBy "TEST_VALUE" -InitialServiceCode "TEST_VALUE" -EndOn "TEST_VALUE" -AvailableCompanies "TEST_VALUE" -ProgramJobTypes "TEST_VALUE" -MaximumRepetitions "TEST_VALUE" -UnitOfMeasure "TEST_VALUE" -HasPriceChart "TEST_VALUE" -IsSentriconInstallationService "TEST_VALUE" -IsSentriconMonitoringService "TEST_VALUE" -IsSentriconRemovalService "TEST_VALUE" -HasSentriconInstallationInitialService "TEST_VALUE" -IsWorkOrder "TEST_VALUE" -MinimumRoundForFullProgram "TEST_VALUE" -MinimumRoundForCAW "TEST_VALUE" -ProgramSpecification "TEST_VALUE" -ProgramCodeIsSpecial "TEST_VALUE" -CanBeServiceCall "TEST_VALUE" -Descriptions "TEST_VALUE" -BranchIDs "TEST_VALUE" -UnitOfMeasureId "TEST_VALUE" -BillingType "TEST_VALUE" -IsAutoRenew "TEST_VALUE" -IncludeInConfirmationLetter "TEST_VALUE" -EstimateServiceCode "TEST_VALUE" -IsCancelDateRequired "TEST_VALUE" -IsCancelReasonRequired "TEST_VALUE" -IsEstimatedByRequired "TEST_VALUE" -IsRejectReasonRequired "TEST_VALUE" -IsRouteRequired "TEST_VALUE" -IsSizeRequired "TEST_VALUE" -IsSoldByRequired "TEST_VALUE" -IsSoldDateRequired "TEST_VALUE" -IsSourceRequired "TEST_VALUE" -LockSoldCancelDate "TEST_VALUE" -ServiceCategory "TEST_VALUE" -BudgetId "TEST_VALUE" -DontPrintInvoice "TEST_VALUE" -LockSchedule "TEST_VALUE" -IsMobile "TEST_VALUE" -IsWebAvailable "TEST_VALUE" -HtmlBackgroundColor "TEST_VALUE" -HtmlForegroundColor "TEST_VALUE" -HasAutoRenewDate "TEST_VALUE"
            #$NewObject | Should -BeOfType ProgramCodes
            #$NewObject.property | Should -Be 0
        }
    }
}
