#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAProgramProductionBySalesPersonRequest' {
    Context 'RGSAProgramProductionBySalesPersonRequest' {
        It 'Initialize-RGSAProgramProductionBySalesPersonRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAProgramProductionBySalesPersonRequest -CompanyIDs "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE" -EmployeeIDs "TEST_VALUE" -DoneDateRange "TEST_VALUE" -CustomDoneDateRange "TEST_VALUE" -SoldDateRange "TEST_VALUE" -CustomSoldDateRange "TEST_VALUE" -PaidDateRange "TEST_VALUE" -CustomPaidDateRange "TEST_VALUE"
            #$NewObject | Should -BeOfType ProgramProductionBySalesPersonRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
