#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAProgramCancelReasonStatsCriteria' {
    Context 'RGSAProgramCancelReasonStatsCriteria' {
        It 'Initialize-RGSAProgramCancelReasonStatsCriteria' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAProgramCancelReasonStatsCriteria -CompanyIDs "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE" -DateRange "TEST_VALUE" -CustomDateRange "TEST_VALUE" -CancelCodes "TEST_VALUE"
            #$NewObject | Should -BeOfType ProgramCancelReasonStatsCriteria
            #$NewObject.property | Should -Be 0
        }
    }
}
