#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSARevenueRemaining' {
    Context 'RGSARevenueRemaining' {
        It 'Initialize-RGSARevenueRemaining' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSARevenueRemaining -TotalIncompleteServices "TEST_VALUE" -TotalCompletedAndUnpaid "TEST_VALUE" -InstallmentChargesNotPosted "TEST_VALUE" -UnpaidPostedInstallments "TEST_VALUE"
            #$NewObject | Should -BeOfType RevenueRemaining
            #$NewObject.property | Should -Be 0
        }
    }
}
