#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaRoundCycleCompanyDetail' {
    Context 'RgSaRoundCycleCompanyDetail' {
        It 'Initialize-RgSaRoundCycleCompanyDetail' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaRoundCycleCompanyDetail -ServiceCode "TEST_VALUE" -NumberOfServices "TEST_VALUE" -Size "TEST_VALUE" -DollarAmount "TEST_VALUE" -CompanyName "TEST_VALUE" -BranchNumber "TEST_VALUE" -CompanyID "TEST_VALUE"
            #$NewObject | Should -BeOfType RoundCycleCompanyDetail
            #$NewObject.property | Should -Be 0
        }
    }
}
