#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaRoundCycleDetail' {
    Context 'RgSaRoundCycleDetail' {
        It 'Initialize-RgSaRoundCycleDetail' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaRoundCycleDetail -ServiceCode "TEST_VALUE" -NumberOfServices "TEST_VALUE" -Size "TEST_VALUE" -DollarAmount "TEST_VALUE"
            #$NewObject | Should -BeOfType RoundCycleDetail
            #$NewObject.property | Should -Be 0
        }
    }
}
