#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSASalesByEmployeeBase' {
    Context 'RGSASalesByEmployeeBase' {
        It 'Initialize-RGSASalesByEmployeeBase' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSASalesByEmployeeBase -EmployeeID "TEST_VALUE" -FirstName "TEST_VALUE" -LastInitial "TEST_VALUE" -GrossSales "TEST_VALUE" -NetSales "TEST_VALUE"
            #$NewObject | Should -BeOfType SalesByEmployeeBase
            #$NewObject.property | Should -Be 0
        }
    }
}
