#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSASalesByEmployeeRequest' {
    Context 'RGSASalesByEmployeeRequest' {
        It 'Initialize-RGSASalesByEmployeeRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSASalesByEmployeeRequest -DateRange "TEST_VALUE" -CustomDateRange "TEST_VALUE" -CompanyIDs "TEST_VALUE" -EmployeeIds "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE" -SourceCodes "TEST_VALUE" -Prepaid "TEST_VALUE" -IncludeSkippedServices "TEST_VALUE" -FullOrPartial "TEST_VALUE"
            #$NewObject | Should -BeOfType SalesByEmployeeRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
