#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaSeasonSummaryByRoundCycleCriteria' {
    Context 'RgSaSeasonSummaryByRoundCycleCriteria' {
        It 'Initialize-RgSaSeasonSummaryByRoundCycleCriteria' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaSeasonSummaryByRoundCycleCriteria -CompanyIDs "TEST_VALUE" -ProgramDefinitionIDs "TEST_VALUE" -RouteCodes "TEST_VALUE" -ResidentialCommercial "TEST_VALUE" -ServiceYear "TEST_VALUE" -ServiceRenewalType "TEST_VALUE" -Prepaid "TEST_VALUE" -ShowNetPrices "TEST_VALUE"
            #$NewObject | Should -BeOfType SeasonSummaryByRoundCycleCriteria
            #$NewObject.property | Should -Be 0
        }
    }
}
