#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAServiceCallResponseRates' {
    Context 'RGSAServiceCallResponseRates' {
        It 'Initialize-RGSAServiceCallResponseRates' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAServiceCallResponseRates -ServiceCallsScheduled "TEST_VALUE" -ServiceCallsCompleted "TEST_VALUE" -ResponseTime "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceCallResponseRates
            #$NewObject.property | Should -Be 0
        }
    }
}
