#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaServiceAllocationItem' {
    Context 'RgSaServiceAllocationItem' {
        It 'Initialize-RgSaServiceAllocationItem' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaServiceAllocationItem -HistoryAllocationID "TEST_VALUE" -HistoryID "TEST_VALUE" -AmountApplied "TEST_VALUE" -HistoryAmount "TEST_VALUE" -TransactionDate "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceAllocationItem
            #$NewObject.property | Should -Be 0
        }
    }
}
