#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaServiceAllocationRecord' {
    Context 'RgSaServiceAllocationRecord' {
        It 'Initialize-RgSaServiceAllocationRecord' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaServiceAllocationRecord -ServiceID "TEST_VALUE" -InvoiceNumber "TEST_VALUE" -Start "TEST_VALUE" -VarEnd "TEST_VALUE" -PrepayDescription "TEST_VALUE" -TotalServiceCharge "TEST_VALUE" -TotalApplied "TEST_VALUE" -Allocations "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceAllocationRecord
            #$NewObject.property | Should -Be 0
        }
    }
}
