#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaSkipServicesAPIResult' {
    Context 'RgSaSkipServicesAPIResult' {
        It 'Initialize-RgSaSkipServicesAPIResult' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaSkipServicesAPIResult -AllServices "TEST_VALUE" -NonServiceable "TEST_VALUE" -Percentage "TEST_VALUE" -NonServiceDetails "TEST_VALUE"
            #$NewObject | Should -BeOfType SkipServicesAPIResult
            #$NewObject.property | Should -Be 0
        }
    }
}
