#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSASkipServicesRequest' {
    Context 'RGSASkipServicesRequest' {
        It 'Initialize-RGSASkipServicesRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSASkipServicesRequest -DateRange "TEST_VALUE" -ServiceCodes "TEST_VALUE" -EmployeeIDs "TEST_VALUE"
            #$NewObject | Should -BeOfType SkipServicesRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
