#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSAStringRange' {
    Context 'RGSAStringRange' {
        It 'Initialize-RGSAStringRange' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSAStringRange -MinValue "TEST_VALUE" -MaxValue "TEST_VALUE"
            #$NewObject | Should -BeOfType StringRange
            #$NewObject.property | Should -Be 0
        }
    }
}
