#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaTaxSimple' {
    Context 'RgSaTaxSimple' {
        It 'Initialize-RgSaTaxSimple' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaTaxSimple -Id "TEST_VALUE" -Position "TEST_VALUE" -Description "TEST_VALUE" -Amount "TEST_VALUE"
            #$NewObject | Should -BeOfType TaxSimple
            #$NewObject.property | Should -Be 0
        }
    }
}
