#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSATaxSimple' {
    Context 'RGSATaxSimple' {
        It 'Initialize-RGSATaxSimple' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSATaxSimple -Id "TEST_VALUE" -Position "TEST_VALUE" -Description "TEST_VALUE" -Amount "TEST_VALUE"
            #$NewObject | Should -BeOfType TaxSimple
            #$NewObject.property | Should -Be 0
        }
    }
}
