#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSATelematicsTrackingTime' {
    Context 'RGSATelematicsTrackingTime' {
        It 'Initialize-RGSATelematicsTrackingTime' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSATelematicsTrackingTime -WorkingTimeStart "TEST_VALUE" -WorkingTimeStop "TEST_VALUE"
            #$NewObject | Should -BeOfType TelematicsTrackingTime
            #$NewObject.property | Should -Be 0
        }
    }
}
