#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaTelematicsTrackingConfiguration' {
    Context 'RgSaTelematicsTrackingConfiguration' {
        It 'Initialize-RgSaTelematicsTrackingConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaTelematicsTrackingConfiguration -MoveSampleIntervalSec "TEST_VALUE" -IdleSampleIntervalSec "TEST_VALUE" -CompassDegrees "TEST_VALUE" -SquashingIntervalSec "TEST_VALUE"
            #$NewObject | Should -BeOfType TelematicsTrackingConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
