#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaTimeSpan' {
    Context 'RgSaTimeSpan' {
        It 'Initialize-RgSaTimeSpan' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaTimeSpan -Ticks "TEST_VALUE" -Days "TEST_VALUE" -Hours "TEST_VALUE" -Milliseconds "TEST_VALUE" -Minutes "TEST_VALUE" -Seconds "TEST_VALUE" -TotalDays "TEST_VALUE" -TotalHours "TEST_VALUE" -TotalMilliseconds "TEST_VALUE" -TotalMinutes "TEST_VALUE" -TotalSeconds "TEST_VALUE"
            #$NewObject | Should -BeOfType TimeSpan
            #$NewObject.property | Should -Be 0
        }
    }
}
