#
# Real Green Service Assistant Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSaPS' -name 'RGSATitle' {
    Context 'RGSATitle' {
        It 'Initialize-RGSATitle' {
            # a simple test to create an object
            #$NewObject = Initialize-RGSATitle -Id "TEST_VALUE" -TitleDesc "TEST_VALUE"
            #$NewObject | Should -BeOfType Title
            #$NewObject.property | Should -Be 0
        }
    }
}
