#
# RGS Common API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: v01
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'RealGreenSAPS' -name 'RgSaTopic' {
    Context 'RgSaTopic' {
        It 'Initialize-RgSaTopic' {
            # a simple test to create an object
            #$NewObject = Initialize-RgSaTopic -Id "TEST_VALUE" -Description "TEST_VALUE" -DescriptionFrench "TEST_VALUE" -DescriptionSpanish "TEST_VALUE"
            #$NewObject | Should -BeOfType Topic
            #$NewObject.property | Should -Be 0
        }
    }
}
